using SlayTheSpireSolver.RulesEngine.Values;

namespace SlayTheSpireSolver.RulesEngine;

public record ResolvableGameStatePossibility(ResolvableGameState ResolvableGameState, Probability Probability);